### ISSUE TITLE
Testing click event generates MissingComponentMethodReferencedByAction

### ISSUE THREAD

**Issue by miggiboy** [calebporzio/livewire#114]
Hi awesome Livewire people!

Basically I'am building a resource table component to show lists of my eloquent models

**Describe the bug**
Cannot use click() method to test my livewire component because it causes MissingComponentMethodReferencedByAction when I run this code
$table->click('[wire:click="next"]'); 

**To Reproduce**
See this test
https://github.com/miggiboy/livewire-resource-table-demo/blob/master/tests/Feature/ResourceTableTest.php#L83

**Expected behavior**
I was expecting that it would work like in this demo https://calebporzio.com/a-bunch-of-cool-new-things-in-laravel-livewire/

**Comment by calebporzio** [comment]
Hi @miggiboy, Livewire is throwing that error because it is trying to find a method called "click" inside your component.

That testing API has been removed a long time ago. It's too much to maintain at the moment. So you will have to stick with the "->call()" and "->set()" testing strategy. Notice what you're trying to do isn't in the Testing documentation.

Thanks.
