### ISSUE TITLE
Make it clear that Javascript is required

### ISSUE THREAD

**Issue by rverrips** [calebporzio/livewire#118]
**Is your feature request related to a problem? Please describe.**
It doesn't happen often, but some people may access your site with a browser that doesn't support javascript or they may have javascript turned off.   Current trend for sites these days is to just do nothing about this, but considering Livewire is so much better than other Javascript implementations, I'd expect it to do a little better. 

Also unlike other Javascript implementations which usually just render nothing if Javascript is turned off, trying to use Livewire components without javascript results in some strange behavior because the php/blade elements still render, i.e. you'll have an input block or button rendered by php/blade, but nothing happens when you click or press enter.  

**Describe the solution you'd like**
Show some clear message that javascript is needed to use this site, and perhaps even don't render the components at all - Wrapping a nice message (perhaps even allow to define this as a parameter passed into @LivewireAssets or even define a blade component with some styling would be great (Include an image of a jellyfish for extra credit)  
```
<noscript type="text/javascript">
                    This website requires javascript support to function properly.
</noscript>
```
**Describe alternatives you've considered**
We can of course leave this up to the web developer using Livewire to implement on their own, but considering it's a problem all developers who implement Livewire may be affected by it would be nice to offer some good "Default" behavior.  

I also believe this is the kind of "Quality of Life" improvement most developers would not even be aware if it isn't there, but those who are tasked to deal with it will be thankful it is when an end user simply says "Your site does not work" and there's no context within which to start troubleshooting.  

(This is by no means urgent, but something I feel is important to discuss)

**Comment by calebporzio** [comment]
Good points @rverrips. Right now, I'm not sure there's a good way to address this from Livewire itself.

1. Like you mentioned, I DO think this is something that devs should address on their own.
2. You make a good point though that Livewire appears to work unlike other JS frameworks and that could cause confusion.
3. Because we can't execute JS if JS isn't enabled that takes a bunch of solutions off the table.
4. The noscript tag would be fine, but because we can't use JavaScript, the dev would be required to put the "@livewireAssets" tag somewhere where the <noscript> tag would be visible.  (now that I say that it "could" be styled with css and stuck to the top or something).
5. I generally stay away from adding things that will be displayed visually on the page. (like what if the app already has its own message to address this, we would need to provide an option to disable ours...)

Ok, after talking through all this. I don't think this is something I want to add ATM. I'm going to close this for now, but someone can re-open it if they think the conversation needs continuing.

Thanks for the well thought out Issue.

**Comment by rverrips** [comment]
I understand and agree with you.  

If we revisit an possible option could be:
4/5 - Yes, inside the no script with a blade include from vendors with a default message, but it could be copied to user resource/view root and then cleared out if the user did not want to show the error message, or be styled there according to the users preference. 

As mentioned, was just hoping to provide what I in my opinion would be some "good defaults" for the framework.

In the never dying words of Emit though, "Everything is Awesome!" ;)
