### ISSUE TITLE
Internet Explorer 11 support

### ISSUE THREAD

**Issue by rverrips** [calebporzio/livewire#119]
**Is your feature request related to a problem? Please describe.**
Similar to issue #118 at present there is a lack of support for Internet Explorer 11 (I believe due to fetch and promises needing a polyfill).  Would be great to support this.   In June 2019 only 3.6% of traffic on the internet is considered to be from IE/Edge which seems negligible, but for some enterprise usage IE11 is still the default browser due to legacy applications etc. A two step approach to replace those legacy solutions with Laravel based ones would be helped if Livewire supported IE11, at least as an optional extra. 

**Describe the solution you'd like**
Having a second instance of livewire.js built with support for IE11 that can be called with either a parameter in @livewireAssets or perhaps as an alternative would be great, say @livewireAssetsMaximumSupport

**Describe alternatives you've considered**
Like "Github" does these days showing a banner stating that IE11 is no longer supported is an option the developer could implement, but considering (to my knowledge) support for fetch and promises can be polyfilled it would be a sad reason to not use Livewire. 

(This is by no means urgent, but something I feel is important to discuss)

**Comment by calebporzio** [comment]
Good call Roy.

The last app I worked on required IE 11 support, so I get it.

As tempting as it is to just ignore it, there are lots of people that require it.

I'd welcome a PR that makes minimal changes to the codebase but get's us to IE 11 support.

Thanks!

**Comment by fakingfantastic** [comment]
Hey there, @rverrips - 

I think this is some good feedback, so thanks for being a good team player! ⛹️‍♂️

I definitely agree that, while IE11 and the like are on the decline, if it's something a polyfil can clean up, or at the least a notice can tip off, it would just make the usability a little better and save some folks some time. 

I'm can try and take a look into this, @calebporzio 

Thanks

**Comment by fakingfantastic** [comment]
Hey ya'll...

Got a proof of concept going: https://github.com/fakingfantastic/livewire/tree/legacy-browser-polyfills

![demo](https://dzwonsemrish7.cloudfront.net/items/0f3a392d1J3X1O27081E/Screen%20Recording%202019-08-05%20at%2001.46%20PM.gif?v=39b804e2)

It was a few of the usual suspects that needed to be polyfilled...

- Array.from
- Array.prototype.flat
- Array.prototype.includes
- Element.prototype.getAttributeNames
- Fetch
- Promise

As stated, my branch is still just a proof of concept on my lunch break. I will clean it all up, and bootstrap this stuff in smarter. @calebporzio - if there's a suggestion of better/standard places to put this in the lib, I'm all ears - otherwise I'll take a crack at it next pass.

🤜

**Comment by calebporzio** [comment]
Hey @fakingfantastic - great work! 

You should create a PR for this so we have a place to discuss the code changes and see the diff easily.

It doesn't have to be a finished branch, it can be a work in progress.

**Comment by fakingfantastic** [comment]
@calebporzio coming in hawt: https://github.com/calebporzio/livewire/pull/126

**Comment by calebporzio** [comment]
Thanks a bunch, man!

**Comment by rverrips** [comment]
You guys are **AWESOME!**
