### ISSUE TITLE
Clear form field after submission

### ISSUE THREAD

**Issue by deep80** [calebporzio/livewire#125]
How am i able to clear off the form fields after successfull form submission ??

**Comment by 2kodes** [comment]
Since form fields are usually set to a variable in the Component class using `wire:model ` you can set those variables to empty after the form submission. 
eg

` public function addContact()
    {
        Contact::create(['email' => $this->email]);
        session()->flash('alert-success', "Contacts saved successfully");
       $this->email="";
    }`

You can also create a function in the component class where you set the public variables to empty

**Comment by deep80** [comment]
Thanks for your reply

I will definitely give it a try

**Comment by calebporzio** [comment]
@2kodes is right. Thanks.

**Comment by Tarhex** [comment]
For new comers, you can simply do `$this->reset()` to reset all fields.

**Comment by andresgutgon** [comment]
Hi, I'm following the [bootcamp.laravel.com/livewire](https://bootcamp.laravel.com/livewire) and I have pushed my following of the tutorial in this repo:
https://github.com/andresgutgon/laravel-101

This is the work done so far to move to Livewire the app. I'm doing `reset` but is not cleaning the input:
https://github.com/andresgutgon/laravel-101/commit/88a4509fc2a07094b15dc556f494072718e504b5#diff-c674a4c465a27a863bfc0400431754201f7c3173fa3141cbb0714f03bcba5946R15

Any ideas of what could be? Thanks!

**Comment by andresgutgon** [comment]
Ok I got this one fixed by removing AlpineJS from the bootstrap JS
<img width="444" alt="image" src="https://github.com/livewire/livewire/assets/49499/b96b1673-bf7a-43dd-aab2-0bad94cc9c03">


I found the solution here: https://laracasts.com/discuss/channels/livewire/livewire-modal-freezing-page


Now I have the same problem when editing a component: 
<img width="666" alt="image" src="https://github.com/livewire/livewire/assets/49499/c774dd0e-6e2d-4bba-8205-c90e280b8a09">

My problem was that I did first the bootcamp without Livewire and this was a leftover. What I learned is if you use Livewire in a page it's injected automatically together with AlpineJS by Laravel. Which a super nice DX experience!
