### ISSUE TITLE
Update hooks not triggering after mutation

### ISSUE THREAD

**Issue by germangamboa95** [calebporzio/livewire#142]
If I have an action ` <button wire:click="addOne"></button>` that does the following 

```  php
 public function addOne(): void
 {
     $this->counter++;
 }
 ```  

neither of this methods will trigger  in the component

```  php
public function updated($name, $value)
    {
        dd($name, $value);
    }

    public function updatedCounter($value)
    {
        dd($value);
    }

```
I expect that mutating a component property will trigger an update hook.

**Comment by webong** [comment]
Hey @calebporzio I see that the latest release now scopes `->updated()` and `->updating()`  to property updates only, not actions. I would love to know your reason behind this change as it affected how I had written my components earlier.

**Comment by calebporzio** [comment]
Yeah, I decided to scope it to properties, because I though more people would think it behaves that way AND the `$name, $value` params wouldn't make sense for method calls. I'd almost rather have a different hook for method calls.

Also, my thought was, if you want to hook into a method call, you could just add the code inside the method.

Maybe show me some code that is now much more difficult.

I also realize this is a breaking change and probably should have been added in another version. Sorry about that.

**Comment by germangamboa95** [comment]
I was thinking it behaved similar to Vue and watched properties. @webong and what is the difference between a property update and an action that updates a property?

**Comment by calebporzio** [comment]
Aaah, I see - you are expecting ANY mutation of a property to run the "updated" and "updating" methods. Interesting - I could see that.

**Comment by calebporzio** [comment]
That would be kind of difficult to implement. But not impossible.

**Comment by webong** [comment]
@germangamboa95 Data binding enables direct property update, as this is different from when an action is triggered to update a property. Livewire also has some [special actions](https://livewire-framework.com/docs/triggering-actions/) that perform direct property update too.

> I was thinking it behaved similar to Vue and watched properties. @webong and what is the difference between a property update and an action that updates a property?

**Comment by germangamboa95** [comment]
@calebporzio  th hink the docs on lifecycle hooks gave the wrong impression when it comes to that. I think it can be added explicitly via prefacing the property with set  `$this->setCounter++` and then we can hook into `__set` and find the property we need to mutate. I'm willing to make  a PR for it if that is a behavior we want in the framework

**Comment by calebporzio** [comment]
Hey @germangamboa95, if we did something like that, I'd rather see `$this->set('counter', $this->counter+1);`

Although, I'm not sure an addition like that is necessary at the moment.

I'm open to adding something like this, I just want someone to provide a clear code example of a realistic scenario where this is needed.

Closing for now, feel free to re-open.

**Comment by natanaelsinisalo** [comment]
I know this is quite an old issue, but I just wasted 1.5 hours of my life while debugging my component because I didn't know that the lifecycle hooks doesn't run while mutating a property from a component method. Maybe there should at least be a note on this in the [lifecycle hooks documentation](https://laravel-livewire.com/docs/2.x/lifecycle-hooks) of this behavior 😆

I also found a realistic scenario when having something like `$this->set('property', $value);` would be really handy. This scenario is somewhat complex, so I'll try to explain the steps on how I run into this issue.

I started implementing data tables (by following the [Surge screencasts](https://laravel-livewire.com/screencasts/s7-intro)) into my app. Soon I ran into an issue where I needed to have more fields in the create/edit modal than my screen height was. It seems that the modal component was built in a way that doesn't support modal scrolling. So I refactored my modal to support scroll bar. So far so good.

But then I had a page where I had more content in the page itself than my monitor height was, so there was a scroll bar in the body. So now I had two scroll bars while opening the modal with a scroll bar in a page like that.

A common way to solve this issue is to disable the body scroll bar by toggling something like style="overflow-y: hidden;" in the body tag when opening/closing the modal.

I'm using Livewire to show/hide the modal (same as in the Surge example) so I started to implement the body scroll bar disabling with the `$this->dispatchBrowserEvent()` method.

The most logical place for this seems to be:

```
    public function updatedShowEditModal()
    {
        $this->dispatchBrowserEvent('disable-body-scroll', [
                'value' => $this->showEditModal
        ]);
    }
```

The modal itself has `show: @entangle($attributes->wire('model'))`, so it triggers this hook whenever I close the modal. Things gets problematic when using custom methods such as create() and edit() to handle the opening logic of the modal:


```
    public function create()
    {
        if ($this->user->getKey()) {
            $this->user = $this->makeBlankUser();
        }

        $this->showEditModal = true;
    }
```

But now since `$this->showEditModal = true;` doesn't trigger any lifecycle hooks, I have to call `$this->dispatchBrowserEvent()` manually in multiple methods (create(), edit() and save()) to achieve what I need.

I'm using a custom macro `$this->toggleDisableBodyScroll($bool);` to tidy up the code a little, but I would much rather use `$this->set('showEditModal', $this->showEditModal);` or `$this->toggle('showEditModal') to avoid unnecessary repetition ☺️

**Comment by natanaelsinisalo** [comment]
REOPEN

I know this is quite an old issue, but I just wasted 1.5 hours of my life while debugging my component because I didn't know that the lifecycle hooks doesn't run while mutating a property from a component method. Maybe there should at least be a note on this in the [lifecycle hooks documentation](https://laravel-livewire.com/docs/2.x/lifecycle-hooks) of this behavior 😆

I also found a realistic scenario when having something like `$this->set('property', $value);` would be really handy. This scenario is somewhat complex, so I'll try to explain the steps on how I run into this issue.

I started implementing data tables (by following the [Surge screencasts](https://laravel-livewire.com/screencasts/s7-intro)) into my app. Soon I ran into an issue where I needed to have more fields in the create/edit modal than my screen height was. It seems that the modal component was built in a way that doesn't support modal scrolling. So I refactored my modal to support scroll bar. So far so good.

But then I had a page where I had more content in the page itself than my monitor height was, so there was a scroll bar in the body. So now I had two scroll bars while opening the modal with a scroll bar in a page like that.

A common way to solve this issue is to disable the body scroll bar by toggling something like style="overflow-y: hidden;" in the body tag when opening/closing the modal.

I'm using Livewire to show/hide the modal (same as in the Surge example) so I started to implement the body scroll bar disabling with the `$this->dispatchBrowserEvent()` method.

The most logical place for this seems to be:

```
    public function updatedShowEditModal()
    {
        $this->dispatchBrowserEvent('disable-body-scroll', [
                'value' => $this->showEditModal
        ]);
    }
```

The modal itself has `show: @entangle($attributes->wire('model'))`, so it triggers this hook whenever I close the modal. Things gets problematic when using custom methods such as create() and edit() to handle the opening logic of the modal:


```
    public function create()
    {
        if ($this->user->getKey()) {
            $this->user = $this->makeBlankUser();
        }

        $this->showEditModal = true;
    }
```

But now since `$this->showEditModal = true;` doesn't trigger any lifecycle hooks, I have to call `$this->dispatchBrowserEvent()` manually in multiple methods (create(), edit() and save()) to achieve what I need.

I'm using a custom macro `$this->toggleDisableBodyScroll($bool);` to tidy up the code a little, but I would much rather use `$this->set('showEditModal', $this->showEditModal);` or `$this->toggle('showEditModal') to avoid unnecessary repetition ☺️
