### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by tillkruss** [calebporzio/livewire#220]
Is there any way to listen for events or execute a callback when a new item arrives?

We'd like to play a sound when a new message appears.

```html

<div wire:poll.5s="$refresh">

    @foreach ($messages as $message)
          <div class="message" wire:transition.slide.down.1s>
              <!-- snip -->
          </div>
    @endforeach

</div>
```

**Comment by davidpiesse** [comment]
If you use the event system you can.

https://livewire-framework.com/docs/events/

Listening for events in JavaScript.

Given your current snippet, maybe a check in the component for a message
count > 0? Or a notification from elsewhere in your app?

A custom refresh method could then be called instead of $refresh that
checks for new messages and emits the event.

**Comment by tillkruss** [comment]
@davidpiesse: Thanks, could you explain that in pseudo code?

**Comment by davidpiesse** [comment]
Sure!

In the Livewire View
```html
<div wire:poll.5s="checkForNewMessages">
    @foreach ($messages as $message)
          <div class="message" wire:transition.slide.down.1s>
              <!-- snip -->
          </div>
    @endforeach
    <audio id="audio" src="http://www.soundjay.com/button/beep-07.wav" autoplay="false" ></audio>
    <script>
    window.livewire.on('new-messages', param => {
        //play sound
        document.getElementById("audio").play();
    })
    </script>
</div>
```

Livewire Component
```php
    public function checkForNewMessages() {
    	$messages = Messages::checkForNew();
        
        if($messages->count > 0) {
        	$this->emit('new-messages');
        }
        
        //...
    }
```

**Comment by tillkruss** [comment]
Thanks a lot. I ended up calling `$this->emit('new-messages');` inside the `render()` function itself.

**Comment by calebporzio** [comment]
Good stuff. Just for funzies I've been experimenting with putting component `<script>`s inside my apps normal "scripts" Blade stack.

So a component's view would look like this:

```
<div>
    <button id="foo"></button>
</div>

@push('scripts')
<script>
document.querySelector('button')....
</script>
@endpush
```

Your stack exists in your normal base layout file, and obviously doesn't get updated when Livewire is updated.

It seems like a great solution because you don't have render blocking inline javascript in your component
