### ISSUE TITLE
Publish assets as files instead of dynamic routes

### ISSUE THREAD

**Issue by tillkruss** [calebporzio/livewire#223]
Serving the `livewire.js` file through PHP makes it harder to cache.

Can we have a `vendor:publish` command like other packages? I'm happy to submit a PR.

**Comment by calebporzio** [comment]
`vendor:publish` adds setup friction. It's kind of a nitpicky thing of mine.

In what way is it harder to cache? I add headers to have browsers cache the routes as if they were files. Also, it's all cache busted when Livewire updates automatically. I like having control over serving the assets.

**Comment by tillkruss** [comment]
It's just a bad practice because a PHP request is fired, instead of Nginx serving a static asset. A middleware might even do I/O before the asset is returned, things like Telescope record the request or worst case the request is counted as a visit.

## One

We should at least add the expries and etag header:

```
Expires: Thu, 31 Dec 2037 23:55:55 GMT
ETag: W/"5d48b374-5a9"
```

## Two

I assume most people have a composer file like this anyhow:

```json
{
    "post-autoload-dump": [
        "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
        "@php artisan package:discover --ansi",
        "@php artisan vendor:publish --force --tag=horizon-assets --ansi",
        "@php artisan vendor:publish --force --tag=telescope-assets --ansi"
    ]
```

So adding another line isn't a big deal.

## Three

We can still keep it the default to serve assets via PHP, but I'd want a way to publish the assets.

I'm happy to submit a PR if you're open to it.

**Comment by tillkruss** [comment]
Related: #235

**Comment by calebporzio** [comment]
Yeah, let's get a config file going (in that PR). I wouldn't want to both publish the assets AND the config file at the same time though.

I still don't fully understand why this would be necessary. If the route is cached, it's only a "PHP" request the first time for the user.

I imagine MOST people wanting the assets served via PHP.

However, I'm open to make this configurable, I would just want clarity on the following things:

A) I don't want to publish the assets along with the config file (maybe make these `artisan livewire:x` commands)
B) What happens when we deploy a new version with updated JS. Do they have to re-publish? It seems like a an issue. I imagine people forgetting to re-publish or whatever, and they have PHP that is updated, but JS that's not. Just want some clarity here.

**Comment by calebporzio** [comment]
Also, a PR for the headers would be great.

**Comment by tillkruss** [comment]
> Also, a PR for the headers would be great.

See #240 for better cache headers.

The PR is a great example of why serving static assets with PHP is bad. It's a complex topic, do we really want to maintain that logic? Nginx could handle all of that logic.

You can read more about caching headers here:

- https://annevankesteren.nl/2005/05/http-304
- https://airbrake.io/blog/http-errors/304-not-modified
- http://edn.embarcadero.com/article/38123

**Comment by tillkruss** [comment]
> A) I don't want to publish the assets along with the config file (maybe make these artisan livewire:x commands)

Sure, no problem. We can make the assets optional by using two separate tags. 

> B) What happens when we deploy a new version with updated JS. Do they have to re-publish? It seems like an issue. I imagine people forgetting to re-publish or whatever, and they have PHP that is updated, but JS that's not. Just want some clarity here.

Totally, that why most Horizon and Telesope users have Composer publish the assets for them after each update:

```json
{
    "post-autoload-dump": [
        "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
        "@php artisan package:discover --ansi",
        "@php artisan vendor:publish --force --tag=horizon-assets --ansi",
        "@php artisan vendor:publish --force --tag=telescope-assets --ansi"
    ]
}
```
