### ISSUE TITLE
route:cache does not include the Livewire endpoint

### ISSUE THREAD

**Issue by oddarne74** [calebporzio/livewire#82]
**Describe the bug**
The Livewire endpoint at `/livewire/message` is not cached when running `php artisan route:cache`

**To Reproduce**
* Follow the [Quickstart guide](https://livewire-framework.com/docs/quickstart/) to get the example app up and running.
* Verify that the counter works.
* Run `php artisan route:cache`
* Clicking `+` or `-` now results in a 404 response

**Expected behavior**
The Livewire endpoint is included in the route cache, and the app still works.

**Comment by davidpiesse** [comment]
Hi @oddarne74 ,

The Message endpoint should probably be hidden in most circumstances, but I can see how here is where you want *everything* listed and cached. The same would go for the keep-alive.

Does the livewire.js route appear in the cached lsit?

I havehad this on other packages and its because of
"Closure based routes cannot be cached. To use route caching, you must convert any Closure routes to controller classes."

I would think its because they are registered in the Service Provider here and are only loaded when they need to be for Livewire (unlike normal controller routes):
https://github.com/calebporzio/livewire/blob/a07595ef038e11a004a73efb6c80bd0ae9cb635f/src/LivewireServiceProvider.php#L48-L56

David

**Comment by calebporzio** [comment]
Thanks David, that's exactly why this is happening.

However, I DO want to support "artisan route:cache", so I will make these routes publicly visible in the latest release (this problem will be fixed): v0.1.2 (not out just yet)

**Comment by calebporzio** [comment]
Thanks David, that's exactly why this is happening.

However, I DO want to support "artisan route:cache", so I will make these routes publicly visible in the latest release (this problem will be fixed): v0.1.2 (not out just yet)
